name: Build Docker images

on:
  push:

env:
  GROUP_NAME: hoanicross
  DOCKER_METADATA_OUTPUT_VERSION: v4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [apache, fpm]
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta ${{ matrix.image }} image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.GROUP_NAME }}/${{ matrix.image }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build ${{ matrix.image }} image
        id: build
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.image }}/Dockerfile
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.GROUP_NAME }}/${{ matrix.image }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ apache, fpm ]
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta ${{ matrix.image }} image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.GROUP_NAME }}/${{ matrix.image }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create manifest list and push ${{ matrix.image }} image
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GROUP_NAME }}/${{ matrix.image }}@sha256:%s ' *)
      - name: Inspect ${{ matrix.image }} image
        run: |
          docker buildx imagetools inspect ${{ env.GROUP_NAME }}/${{ matrix.image }}:${{ steps.meta.outputs.version }}
